name: Deploy NestJS to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"

      - name: npm install, build, and test
        run: |
          npm ci
          npx prisma generate
          npm run build
          npm run test --if-present

      - name: Prepare deployment package
        run: |
          mkdir deploy
          cp -r dist deploy/
          cp package.json deploy/
          cp package-lock.json deploy/
          cp -r prisma deploy/
            # .deployment
            # .nvmrc

      - name: Zip artifact
        run: |
          cd deploy
          zip -r ../app.zip .

      # - name: Upload artifact for deployment job
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: node-app
      #     path: |
      #       dist
      #       package.json
      #       package-lock.json
      #       prisma
      #       nest-cli.json
      #       tsconfig.json
      #       tsconfig.build.json
      #       .deployment
      #       .nvmrc

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "quize-builder-backend"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9819404B8AD64F7A9742EAA086D5CE49 }}
          package: app.zip

  # # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build

  #   steps:
  #     - name: Download artifact from build job
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: node-app

  #     - name: Set up Node.js version
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: "22.x"

  #     - name: Install dependencies
  #       run: |
  #         npm ci --production
  #         npx prisma generate

  #     - name: Verify node_modules exists
  #       run: |
  #         if [ ! -d "node_modules" ] || [ -z "$(ls -A node_modules)" ]; then
  #           echo "ERROR: node_modules is empty or missing!"
  #           exit 1
  #         fi
  #         echo "node_modules verified: $(du -sh node_modules | cut -f1)"
  #         ls -la node_modules | head -20

  #     - name: "Deploy to Azure Web App"
  #       id: deploy-to-webapp
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: "quize-builder-backend"
  #         slot-name: "Production"
  #         package: .
  #         publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_9819404B8AD64F7A9742EAA086D5CE49 }}
  #         startup-command: "node dist/src/main.js"
